// Repository
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
export const COLOR_SCHEME_REPOSITORY = 'COLOR_SCHEME_REPOSITORY';
export const GROUP_COLOR_SCHEME_REPOSITORY = 'GROUP_COLOR_SCHEME_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_IMAGE_REPOSITORY = 'PRODUCT_IMAGE_REPOSITORY';
export const GROUP_REPOSITORY = 'GROUP_REPOSITORY';



